version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - D:/microservices/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"
    depends_on:
      - prometheus