version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - D:/microservices/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.enable-lifecycle'

  grafana:
    container_name: grafana
    image: bitnami/grafana:latest
    ports:
      - "4000:3000"
    volumes:
      - ./grafana-data/:/opt/bitnami/grafana/data/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus