global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "microservices"
    metrics_path: /actuator/prometheus
    scheme: http
    scrape_interval: 5s
    scrape_timeout: 3s
    honor_labels: true
    static_configs:
      - targets:
          - "host.docker.internal:8083"
          - "host.docker.internal:8089"
          - "host.docker.internal:8886"
          - "host.docker.internal:8084"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance