spring:
  application:
    name: artist-service
  config:
    import: optional:configserver:http://localhost:8888/

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true