server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NMWXask/configuration-repository/
          clone-on-start: true
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
          force-pull: false